site_name: Luke's Wiki
theme:
  name: material
  language: zh
  logo: ../logo.png
  site_title: wiki.vexrune.top  # 替换默认的 site_name 显示
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

strict: false

docs_dir: ./docs

site_dir: ./site

homepage: /

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - tables
  - toc:
      permalink: true
  - meta
  - def_list

plugins:
  - search:
      lang:
        - en
        - zh

nav:
  - 索引: index.md
  - 软件技术:
    - 软件: 软件/index.md
    - Java: 软件/java/index.md
    - Python: 软件/python/index.md
    - 前端技术: 软件/前端技术/index.md
    - 数据库: 数据库/index.md
    - 架构师: 软件/架构师/index.md
    - 设计模式: 软件/设计模式/index.md
    - AI: 软件/AI/index.md
    - 面试题: 软件/面试题/index.md
  - 产品经理:
    - 产品经理: 产品经理/index.md
    - 入门基础: 产品经理/入门基础.md
    - 用户分析: 产品经理/用户分析.md
  - 项目管理:
    - 项目管理: 项目管理/index.md
    - PMP: 项目管理/PMP/index.md
    - ACP敏捷管理: 项目管理/ACP敏捷管理/index.md
  - 阅读:
    - 阅读: 阅读/index.md
  - 3D建模:
    - 3D建模: 3D建模/index.md
  - 运维技术:
    - 运维技术: 运维技术/index.md
  - 我的:
    - 我的: 我的/index.md